// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createNote, deleteNote, getCurrentPrincipal, getNote, getPublicConfig, listNotes, type Options, updateNote } from '../sdk.gen';
import type { CreateNoteData, CreateNoteResponse, DeleteNoteData, DeleteNoteResponse, GetCurrentPrincipalData, GetCurrentPrincipalResponse, GetNoteData, GetNoteResponse, GetPublicConfigData, GetPublicConfigResponse, ListNotesData, ListNotesResponse, UpdateNoteData, UpdateNoteResponse } from '../types.gen';

export const deleteNoteMutation = (options?: Partial<Options<DeleteNoteData>>): UseMutationOptions<DeleteNoteResponse, DefaultError, Options<DeleteNoteData>> => {
    const mutationOptions: UseMutationOptions<DeleteNoteResponse, DefaultError, Options<DeleteNoteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteNote({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getNoteQueryKey = (options: Options<GetNoteData>) => createQueryKey('getNote', options);

export const getNoteOptions = (options: Options<GetNoteData>) => queryOptions<GetNoteResponse, DefaultError, GetNoteResponse, ReturnType<typeof getNoteQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getNote({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getNoteQueryKey(options)
});

export const updateNoteMutation = (options?: Partial<Options<UpdateNoteData>>): UseMutationOptions<UpdateNoteResponse, DefaultError, Options<UpdateNoteData>> => {
    const mutationOptions: UseMutationOptions<UpdateNoteResponse, DefaultError, Options<UpdateNoteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateNote({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listNotesQueryKey = (options?: Options<ListNotesData>) => createQueryKey('listNotes', options);

export const listNotesOptions = (options?: Options<ListNotesData>) => queryOptions<ListNotesResponse, DefaultError, ListNotesResponse, ReturnType<typeof listNotesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listNotes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listNotesQueryKey(options)
});

export const createNoteMutation = (options?: Partial<Options<CreateNoteData>>): UseMutationOptions<CreateNoteResponse, DefaultError, Options<CreateNoteData>> => {
    const mutationOptions: UseMutationOptions<CreateNoteResponse, DefaultError, Options<CreateNoteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createNote({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCurrentPrincipalQueryKey = (options?: Options<GetCurrentPrincipalData>) => createQueryKey('getCurrentPrincipal', options);

export const getCurrentPrincipalOptions = (options?: Options<GetCurrentPrincipalData>) => queryOptions<GetCurrentPrincipalResponse, DefaultError, GetCurrentPrincipalResponse, ReturnType<typeof getCurrentPrincipalQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentPrincipal({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentPrincipalQueryKey(options)
});

export const getPublicConfigQueryKey = (options?: Options<GetPublicConfigData>) => createQueryKey('getPublicConfig', options);

export const getPublicConfigOptions = (options?: Options<GetPublicConfigData>) => queryOptions<GetPublicConfigResponse, DefaultError, GetPublicConfigResponse, ReturnType<typeof getPublicConfigQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPublicConfig({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPublicConfigQueryKey(options)
});
