// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateNoteData, CreateNoteResponses, DeleteNoteData, DeleteNoteResponses, GetCurrentPrincipalData, GetCurrentPrincipalResponses, GetNoteData, GetNoteResponses, GetPublicConfigData, GetPublicConfigResponses, ListNotesData, ListNotesResponses, UpdateNoteData, UpdateNoteResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const deleteNote = <ThrowOnError extends boolean = false>(options: Options<DeleteNoteData, ThrowOnError>): RequestResult<DeleteNoteResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteNoteResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/notes/{id}',
    ...options
});

export const getNote = <ThrowOnError extends boolean = false>(options: Options<GetNoteData, ThrowOnError>): RequestResult<GetNoteResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetNoteResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/notes/{id}',
    ...options
});

export const updateNote = <ThrowOnError extends boolean = false>(options: Options<UpdateNoteData, ThrowOnError>): RequestResult<UpdateNoteResponses, unknown, ThrowOnError> => (options.client ?? client).put<UpdateNoteResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/notes/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listNotes = <ThrowOnError extends boolean = false>(options?: Options<ListNotesData, ThrowOnError>): RequestResult<ListNotesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListNotesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/notes',
    ...options
});

export const createNote = <ThrowOnError extends boolean = false>(options: Options<CreateNoteData, ThrowOnError>): RequestResult<CreateNoteResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateNoteResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/notes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getCurrentPrincipal = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentPrincipalData, ThrowOnError>): RequestResult<GetCurrentPrincipalResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCurrentPrincipalResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/me',
    ...options
});

export const getPublicConfig = <ThrowOnError extends boolean = false>(options?: Options<GetPublicConfigData, ThrowOnError>): RequestResult<GetPublicConfigResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetPublicConfigResponses, unknown, ThrowOnError>({ url: '/api/config', ...options });
