// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type UpdateNoteRequest = {
    title: string;
    body: string;
};

export type NoteResponse = {
    id?: string;
    title?: string;
    body?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type CreateNoteRequest = {
    title: string;
    body: string;
};

export type MeResponse = {
    userId?: string;
    organizationId?: string;
    externalSubject?: string;
    externalOrganizationId?: string;
    role?: string;
};

export type PublicConfigResponse = {
    clientId?: string;
    apiHostname?: string;
    redirectUri?: string;
};

export type DeleteNoteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/notes/{id}';
};

export type DeleteNoteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetNoteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/notes/{id}';
};

export type GetNoteResponses = {
    /**
     * OK
     */
    200: NoteResponse;
};

export type GetNoteResponse = GetNoteResponses[keyof GetNoteResponses];

export type UpdateNoteData = {
    body: UpdateNoteRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/notes/{id}';
};

export type UpdateNoteResponses = {
    /**
     * OK
     */
    200: NoteResponse;
};

export type UpdateNoteResponse = UpdateNoteResponses[keyof UpdateNoteResponses];

export type ListNotesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notes';
};

export type ListNotesResponses = {
    /**
     * OK
     */
    200: Array<NoteResponse>;
};

export type ListNotesResponse = ListNotesResponses[keyof ListNotesResponses];

export type CreateNoteData = {
    body: CreateNoteRequest;
    path?: never;
    query?: never;
    url: '/api/notes';
};

export type CreateNoteResponses = {
    /**
     * OK
     */
    200: NoteResponse;
};

export type CreateNoteResponse = CreateNoteResponses[keyof CreateNoteResponses];

export type GetCurrentPrincipalData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type GetCurrentPrincipalResponses = {
    /**
     * OK
     */
    200: MeResponse;
};

export type GetCurrentPrincipalResponse = GetCurrentPrincipalResponses[keyof GetCurrentPrincipalResponses];

export type GetPublicConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type GetPublicConfigResponses = {
    /**
     * OK
     */
    200: PublicConfigResponse;
};

export type GetPublicConfigResponse = GetPublicConfigResponses[keyof GetPublicConfigResponses];
